version: "3.8"

networks:
  default:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:latest
    container_name: services_rabbitmq
    env_file: .env
    networks:
      - default

  api:
    build: ./api
    container_name: services_api
    restart: always
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
    env_file: .env
    networks:
      - default

  listener:
    build: ./listener
    container_name: services_listener
    restart: always
    depends_on:
      - rabbitmq
    env_file: .env
    networks:
      - default
